### ISSUE TITLE
Makefile changes to get musashi to compile under FreeBSD

### ISSUE THREAD

**Issue by tingox** [John-Titor/py68k#2]
I changed the makefile to get musashi to compile under FreeBSD
`tingo@kg-core1$ diff -u Makefile_org Makefile`
`--- Makefile_org	2018-03-20 00:35:54.729223000 +0100`
`+++ Makefile	2018-03-20 00:40:04.426807000 +0100`
`@@ -4,6 +4,9 @@`
` ifeq "$(OS)" "Darwin"`
` CC = clang`
` SO_EXT = dylib`
`+else ifeq "$(OS)" "FreeBSD"`
`+CC = clang`
`+SO_EXT = so`
` else`
` CC = gcc`
` SO_EXT = so`
hope this helps.

**Comment by John-Titor** [comment]
Thanks, integrated.
